name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
        env:
          ARRP_VERSION: ${{ github.event.release.tag_name }}
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/arrp-reborn-${{ github.event.release.tag_name }}.jar
          tag_name: ${{ github.event.release.tag_name }}
